// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: add_private_chat_participants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPrivateChatParticipants = `-- name: AddPrivateChatParticipants :exec
INSERT INTO chat_participants ("chatId", "userId")
VALUES
    ($1, $2),
    ($1, $3)
`

type AddPrivateChatParticipantsParams struct {
	ChatId   pgtype.UUID `json:"chatId"`
	UserId   pgtype.UUID `json:"userId"`
	UserId_2 pgtype.UUID `json:"userId_2"`
}

func (q *Queries) AddPrivateChatParticipants(ctx context.Context, arg AddPrivateChatParticipantsParams) error {
	_, err := q.db.Exec(ctx, addPrivateChatParticipants, arg.ChatId, arg.UserId, arg.UserId_2)
	return err
}
