// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: create_message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages ("userId", "chatId", text)
VALUES ($1, $2, $3)
RETURNING id, text, "userId", "chatId", "createdAt"
`

type CreateMessageParams struct {
	UserId pgtype.UUID `json:"userId"`
	ChatId pgtype.UUID `json:"chatId"`
	Text   string      `json:"text"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserId, arg.ChatId, arg.Text)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.UserId,
		&i.ChatId,
		&i.CreatedAt,
	)
	return i, err
}
