// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCode struct {
	ID        pgtype.UUID      `json:"id"`
	Code      int32            `json:"code"`
	UserId    pgtype.UUID      `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type ChatParticipant struct {
	ChatId pgtype.UUID `json:"chatId"`
	UserId pgtype.UUID `json:"userId"`
}

type Message struct {
	ID        pgtype.UUID      `json:"id"`
	Text      string           `json:"text"`
	UserId    pgtype.UUID      `json:"userId"`
	ChatId    pgtype.UUID      `json:"chatId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type PrivateChat struct {
	ID pgtype.UUID `json:"id"`
}

type User struct {
	ID          pgtype.UUID      `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	Email       string           `json:"email"`
	Description pgtype.Text      `json:"description"`
	Name        string           `json:"name"`
	IsVerified  pgtype.Bool      `json:"isVerified"`
}

type UserFollow struct {
	FollowerId pgtype.UUID `json:"followerId"`
	FolloweeId pgtype.UUID `json:"followeeId"`
}

type UserTag struct {
	ID   pgtype.UUID `json:"id"`
	Text string      `json:"text"`
	Icon string      `json:"icon"`
}

type UserUserTag struct {
	UserId    pgtype.UUID `json:"userId"`
	UserTagId pgtype.UUID `json:"userTagId"`
}
