// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCode struct {
	ID        pgtype.UUID
	Code      int32
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamp
	Email      string
	Name       string
	IsVerified pgtype.Bool
}
