// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: remove_message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const removeMessage = `-- name: RemoveMessage :exec
DELETE FROM "messages"
WHERE "id" = $1 AND "userId" = $2
`

type RemoveMessageParams struct {
	ID     pgtype.UUID `json:"id"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) RemoveMessage(ctx context.Context, arg RemoveMessageParams) error {
	_, err := q.db.Exec(ctx, removeMessage, arg.ID, arg.UserId)
	return err
}
