// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: remove_private_chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const removePrivateChat = `-- name: RemovePrivateChat :exec
DELETE FROM "private_chats" WHERE "id" = $1
`

func (q *Queries) RemovePrivateChat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removePrivateChat, id)
	return err
}
