// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_auth_code.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateAuthCode = `-- name: UpdateAuthCode :one
UPDATE "auth_codes"
SET "code" = $1  -- Replace $1 with the new code value
WHERE "userId" = $2  -- Replace $2 with the user ID
RETURNING "code"
`

type UpdateAuthCodeParams struct {
	Code   int32       `json:"code"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) UpdateAuthCode(ctx context.Context, arg UpdateAuthCodeParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateAuthCode, arg.Code, arg.UserId)
	var code int32
	err := row.Scan(&code)
	return code, err
}
