// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: update_auth_code.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateAuthCode = `-- name: UpdateAuthCode :one
UPDATE auth_codes
SET code = $1  -- Replace $1 with the new code value
WHERE user_id = $2  -- Replace $2 with the user ID
RETURNING code
`

type UpdateAuthCodeParams struct {
	Code   int32
	UserID pgtype.UUID
}

func (q *Queries) UpdateAuthCode(ctx context.Context, arg UpdateAuthCodeParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateAuthCode, arg.Code, arg.UserID)
	var code int32
	err := row.Scan(&code)
	return code, err
}
